# install color theme to xcode
# /Users/rcarlsen/Library/Developer/Xcode/UserData/FontAndColorThemes

- name: Add Solarized Dark theme to Xcode
  copy:
    src: "files/Solarized-Dark FiraCode.dvtcolortheme"
    dest: "{{ansible_env.HOME}}/Library/Developer/Xcode/UserData/FontAndColorThemes/Solarized-Dark FiraCode.dvtcolortheme"
